# Generated by Django 3.1.3 on 2020-12-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token_type',
            field=models.CharField(choices=[('reset', 'reset'), ('login', 'login')], max_length=20),
        ),
    ]
