# Generated by Django 3.1.3 on 2020-12-04 22:44

from django.db import migrations
from boatfight.models import Boat

BOATS = {
    'longship': ('Longship', 5),
    'knarr': ('Knarr', 4),
    'karve': ('Karve', 3),
    'kraken': ('Kraken', 3),
    'faering': ('Faering', 2),
}

def forward(apps, schema_editor):
    for boat_label, boat_data in BOATS.items():
        display_name = boat_data[0]
        units = boat_data[1]

        data = {
            'label': boat_label,
            'units': units,
            'image':  'images/boats/{}/{}.png'.format(
                boat_label, boat_label
            ),
            'imageMap': []
        }
        for i in range(1, units + 1):
            data['imageMap'].append(
                'images/boats/{}/{}.png'.format(boat_label, i)
            )
        boat = Boat(data=data)
        boat.save()


def backward(apps, schema_editor):
    for boat_label, boat_data in BOATS.items():
        boat = Boat.objects.filter(data__label=boat_label)
        boat.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('boatfight', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
