# Generated by Django 3.1.3 on 2020-11-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boatfight', '0003_auto_20201129_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatfightgame',
            name='game_type',
            field=models.CharField(choices=[('salvo', 'Salvo'), ('classic', 'Classic')], default='salvo', max_length=10),
            preserve_default=False,
        ),
    ]
