# Generated by Django 3.1.3 on 2020-11-27 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import namer.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField(default=10000)),
                ('num_players', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('active', 'active'), ('over', 'over')], default='waiting', max_length=20)),
                ('code_name', models.CharField(blank=True, default=namer.models.get_random_name, max_length=100, unique=True)),
                ('current_turn_index', models.IntegerField(default=1)),
                ('last_turn', models.BooleanField(default=False)),
                ('game_type', models.CharField(choices=[('practice', 'practice'), ('normal', 'normal')], default='normal', max_length=25)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bogames.player')),
            ],
        ),
    ]
