# Generated by Django 3.1.3 on 2020-11-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bogames', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='game',
            name='last_turn',
        ),
        migrations.RemoveField(
            model_name='game',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='num_players',
        ),
    ]
