# Generated by Django 3.1.3 on 2020-11-29 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bogames', '0002_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
