# Generated by Django 3.1.3 on 2020-12-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogames', '0002_auto_20201204_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagame',
            name='data',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='datagame',
            name='meta',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='datagameplayer',
            name='data',
            field=models.JSONField(blank=True),
        ),
    ]
