# Generated by Django 3.1.3 on 2020-12-01 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bogames', '0003_auto_20201129_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('challenged', 'challenged'), ('accepted', 'accepted'), ('conceded', 'conceded'), ('ready', 'ready'), ('won', 'won'), ('lost', 'lost')], default='challenged', max_length=10)),
                ('is_current_player', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_gameplayer', to='bogames.player')),
            ],
        ),
    ]
