# Generated by Django 3.1.3 on 2020-12-03 13:52

from django.db import migrations, models
import django.db.models.deletion
import namer.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bogames', '0004_gameplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code_name', models.CharField(blank=True, default=namer.models.get_random_name, max_length=100, unique=True)),
                ('_game_meta', models.TextField(blank=True)),
                ('_game_data', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataGamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_data', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_gameplayer', to='bogames.player')),
            ],
        ),
    ]
