# Generated by Django 3.1.3 on 2020-12-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogames', '0005_datagame_datagameplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagameplayer',
            name='is_current_player',
            field=models.BooleanField(default=False),
        ),
    ]
