# Generated by Django 3.1.3 on 2020-12-03 14:32

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bogames', '0007_auto_20201203_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagame',
            name='_game_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='datagame',
            name='_game_meta',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
