# Generated by Django 3.1.3 on 2020-12-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bogames', '0009_auto_20201203_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datagame',
            old_name='_game_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='datagame',
            old_name='_game_meta',
            new_name='meta',
        ),
    ]
