# Generated by Django 3.1.3 on 2020-12-03 19:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bogames', '0010_auto_20201203_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagame',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='datagame',
            name='meta',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
