# Generated by Django 3.1.3 on 2020-12-04 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bogames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxDotDataGame',
            fields=[
                ('datagame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bogames.datagame')),
            ],
            bases=('bogames.datagame',),
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('datagameplayer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bogames.datagameplayer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxdots.boxdotdatagame')),
            ],
            bases=('bogames.datagameplayer',),
        ),
    ]
