# Generated by Django 3.1.3 on 2020-12-01 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bogames', '0004_gameplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxDotGame',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bogames.game')),
            ],
            bases=('bogames.game',),
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('gameplayer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bogames.gameplayer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxdots.boxdotgame')),
            ],
            bases=('bogames.gameplayer',),
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameplayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxdots.gameplayer')),
            ],
        ),
    ]
