# Generated by Django 3.1.3 on 2020-12-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxdots', '0002_gameboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxdotgame',
            name='_data',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GameBoard',
        ),
    ]
