# Generated by Django 3.1.3 on 2020-12-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxdots', '0003_auto_20201201_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxdotgame',
            name='_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
