# Generated by Django 3.1.3 on 2020-11-14 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borkle.game')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('available_dice_count', models.IntegerField(default=6)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borkle.game')),
                ('gameplayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borkle.gameplayer')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('score_type', models.CharField(max_length=150)),
                ('dice_1_value', models.IntegerField(null=True)),
                ('dice_2_value', models.IntegerField(null=True)),
                ('dice_3_value', models.IntegerField(null=True)),
                ('dice_4_value', models.IntegerField(null=True)),
                ('dice_5_value', models.IntegerField(null=True)),
                ('dice_6_value', models.IntegerField(null=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borkle.turn')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borkle.player'),
        ),
        migrations.CreateModel(
            name='CurrentPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borkle.game')),
                ('gameplayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borkle.gameplayer')),
            ],
            options={
                'unique_together': {('gameplayer', 'game')},
            },
        ),
    ]
