# Generated by Django 3.1.3 on 2020-11-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bogames', '0002_auto_20201127_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorkleGame',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bogames.game')),
                ('max_score', models.IntegerField(default=10000)),
                ('num_players', models.IntegerField(default=1)),
                ('last_turn', models.BooleanField(default=False)),
                ('game_type', models.CharField(choices=[('practice', 'practice'), ('normal', 'normal')], default='normal', max_length=25)),
            ],
            bases=('bogames.game',),
        ),
        migrations.CreateModel(
            name='BorklePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(default=False)),
                ('player_order', models.IntegerField(default=1)),
                ('is_current_player', models.BooleanField(default=False)),
                ('total_score', models.IntegerField(default=0)),
                ('had_last_turn', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bogames.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bogames.player')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('turn_index', models.IntegerField(default=1)),
                ('available_dice_count', models.IntegerField(default=6)),
                ('rolled_dice_1_value', models.IntegerField(blank=True, null=True)),
                ('rolled_dice_2_value', models.IntegerField(blank=True, null=True)),
                ('rolled_dice_3_value', models.IntegerField(blank=True, null=True)),
                ('rolled_dice_4_value', models.IntegerField(blank=True, null=True)),
                ('rolled_dice_5_value', models.IntegerField(blank=True, null=True)),
                ('rolled_dice_6_value', models.IntegerField(blank=True, null=True)),
                ('borkleplayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borkle.borkleplayer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borkle.borklegame')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('score_type', models.CharField(max_length=150)),
                ('scored_dice_1_value', models.IntegerField(blank=True, null=True)),
                ('scored_dice_2_value', models.IntegerField(blank=True, null=True)),
                ('scored_dice_3_value', models.IntegerField(blank=True, null=True)),
                ('scored_dice_4_value', models.IntegerField(blank=True, null=True)),
                ('scored_dice_5_value', models.IntegerField(blank=True, null=True)),
                ('scored_dice_6_value', models.IntegerField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borkle.turn')),
            ],
        ),
    ]
