# Generated by Django 3.1.3 on 2020-11-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='borkleplayer',
            new_name='gameplayer',
        ),
    ]
