# Generated by Django 3.1.3 on 2020-11-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_players',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
