# Generated by Django 3.1.3 on 2020-11-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borkleplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borkle.borklegame'),
        ),
    ]
