# Generated by Django 3.1.3 on 2020-11-15 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import namer.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borkle', '0003_auto_20201114_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code_name',
            field=models.CharField(default=namer.models.get_random_name, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('active', 'active'), ('over', 'over')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
