# Generated by Django 3.1.3 on 2020-11-15 16:31

from django.db import migrations, models
import django.db.models.deletion
import namer.models


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0004_auto_20201115_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borkle.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='code_name',
            field=models.CharField(blank=True, default=namer.models.get_random_name, max_length=100, unique=True),
        ),
    ]
