# Generated by Django 3.1.3 on 2020-11-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0006_gameplayer_player_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='is_current_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turn',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CurrentPlayer',
        ),
    ]
