# Generated by Django 3.1.3 on 2020-11-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0007_auto_20201115_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='rolled_dice_1_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='rolled_dice_2_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='rolled_dice_3_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='rolled_dice_4_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='rolled_dice_5_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='rolled_dice_6_value',
            field=models.IntegerField(null=True),
        ),
    ]
