# Generated by Django 3.1.3 on 2020-11-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0008_auto_20201115_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoreset',
            old_name='dice_1_value',
            new_name='scored_dice_1_value',
        ),
        migrations.RenameField(
            model_name='scoreset',
            old_name='dice_2_value',
            new_name='scored_dice_2_value',
        ),
        migrations.RenameField(
            model_name='scoreset',
            old_name='dice_3_value',
            new_name='scored_dice_3_value',
        ),
        migrations.RenameField(
            model_name='scoreset',
            old_name='dice_4_value',
            new_name='scored_dice_4_value',
        ),
        migrations.RenameField(
            model_name='scoreset',
            old_name='dice_5_value',
            new_name='scored_dice_5_value',
        ),
        migrations.RenameField(
            model_name='scoreset',
            old_name='dice_6_value',
            new_name='scored_dice_6_value',
        ),
    ]
