# Generated by Django 3.1.3 on 2020-11-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0009_auto_20201115_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
