# Generated by Django 3.1.3 on 2020-11-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0010_gameplayer_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='turn_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='scored_dice_1_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='scored_dice_2_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='scored_dice_3_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='scored_dice_4_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='scored_dice_5_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='scored_dice_6_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='rolled_dice_1_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='rolled_dice_2_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='rolled_dice_3_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='rolled_dice_4_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='rolled_dice_5_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='rolled_dice_6_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
