# Generated by Django 3.1.3 on 2020-11-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0011_auto_20201116_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_turn_index',
            field=models.IntegerField(default=1),
        ),
    ]
