# Generated by Django 3.1.3 on 2020-11-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0012_game_current_turn_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_rolls',
            field=models.IntegerField(default=1),
        ),
    ]
