# Generated by Django 3.1.3 on 2020-11-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0013_game_num_rolls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='num_rolls',
            new_name='action_count',
        ),
    ]
