# Generated by Django 3.1.3 on 2020-11-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0014_auto_20201116_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_turn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='had_last_turn',
            field=models.BooleanField(default=False),
        ),
    ]
