# Generated by Django 3.1.3 on 2020-11-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0015_auto_20201116_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='has_rolled',
            field=models.BooleanField(default=False),
        ),
    ]
