# Generated by Django 3.1.3 on 2020-11-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0016_turn_has_rolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreset',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
