# Generated by Django 3.1.3 on 2020-11-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0018_turn_borkle'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('practice', 'practice'), ('normal', 'normal')], default='normal', max_length=25),
        ),
    ]
