# Generated by Django 3.1.3 on 2020-11-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0019_game_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='roll_count',
            field=models.IntegerField(default=0),
        ),
    ]
