# Generated by Django 3.1.3 on 2020-11-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0020_turn_roll_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreset',
            name='roll',
            field=models.IntegerField(default=1),
        ),
    ]
