# Generated by Django 3.1.3 on 2020-11-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borkle', '0021_scoreset_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='borkle',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='has_rolled',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='roll_count',
        ),
    ]
